[package]
name = "common"
type = "lib"
authors = ["Oleh Misarosh <olehmisar@gmail.com>"]
compiler_version = ">=0.39.0"

[dependencies]
protocol_types = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "aztec-packages-v0.72.1", directory = "noir-projects/noir-protocol-circuits/crates/types" }
bignum = { tag = "v0.6.0", git = "https://github.com/noir-lang/noir-bignum/" }
nodash = { tag = "v0.40.0", git = "https://github.com/olehmisar/nodash/" }
