[package]
name = "common"
type = "lib"
authors = ["Oleh Misarosh <olehmisar@gmail.com>"]
compiler_version = ">=0.39.0"

[dependencies]
protocol_types = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "aztec-packages-v0.63.1", directory = "noir-projects/noir-protocol-circuits/crates/types" }
bignum = { tag = "v0.4.2", git = "https://github.com/noir-lang/noir-bignum/" }
nodash = { tag = "v0.39.1", git = "https://github.com/olehmisar/nodash/" }
