[package]
name = "erc20_unshield"
type = "bin"
authors = ["Oleh Misarosh <olehmisar@gmail.com"]
compiler_version = ">=0.39.0"

[dependencies]
common = { path = "../common" }
erc20 = { path = "../erc20" }
